ConSol-Lab/Pumpkin

Cargo.lock, pumpkin-cli/Cargo.toml, pumpkin-cli/src/flatzinc/parser.rs, pumpkin-lib/Cargo.lock
This PR updates the projects dependencies, in particular in response to security alert https://github.com/ConSol-Lab/pumpkin/security/dependabot/1.
This also updates the [flatzinc](https://crates.io/flatzinc) crate to v0.3.20, which breaks the parsing interface. This PR therefore also contains a minor modification to support their new API.
=> Update project dependencies

pumpkin-cli/src/flatzinc/compiler/context.rs, pumpkin-cli/tests/mzn_search/bool_search_provided_directly.expected, pumpkin-cli/tests/mzn_search/bool_search_provided_directly.fzn, pumpkin-cli/tests/mzn_search_test.rs
This fixes the issue where the following fails to parse:
```
var bool: x1 :: output_var;
var bool: x2 :: output_var;
var bool: x3 :: output_var;
solve :: bool_search([x1, x2, x3], input_order, indomain_max) satisfy;
```
This was due to the fact that the flatzinc crate which we use does not know what the type of the provided array is and it then automatically parses it to an array of ints. The fix is to parse int arrays when parsing boolean array but only allowing boolean values in there.
=> Add fix for array of bools being parsed as array of int

pumpkin-cli/Cargo.toml, pumpkin-cli/src/main.rs, pumpkin-cli/tests/helpers/mod.rs
When running `pumpkin-cli --help`, the options are not necessarily clear; and (what is more bothersome), it is not clear from the output what the possible values are for the different options.
This PR aims to address this by adding more descriptive documentation for the different options in combination with clarifying what the possible values are for the different options. All of the documentation now uses the `verbatim_doc_comment` so that it is in line with the rest of our documentation (and more importantly, that clap doesn't perform any weird line-breaking).
=> Adding more descriptive options

pumpkin-lib/src/engine/cp/propagation/propagation_context.rs, pumpkin-lib/src/engine/variables/affine_view.rs, pumpkin-lib/src/engine/variables/domain_id.rs, pumpkin-lib/src/engine/variables/integer_variable.rs, pumpkin-lib/src/engine/variables/literal.rs, pumpkin-lib/src/propagators/element.rs
The element propagator now makes use of lifted explanations, which are smaller than the ones we generated previously. For now we dropped domain consistency, however, in my experiments that does not show up as a detriment. We should consider adding it in again though.
Note: This is not into the master branch, but into the revamp branch.
=> Improve the element propagator with better explanations.

pumpkin-cli/src/flatzinc/compiler/create_search_strategy.rs, pumpkin-cli/tests/mzn_search/seq_search_1.expected, pumpkin-cli/tests/mzn_search/seq_search_1.fzn, pumpkin-cli/tests/mzn_search_test.rs
When constructed a sequenced brancher, the individual branchers should not have the default brancher appended to them. This bug was triggered in the `seq_search_1.fzn` search test.
=> Don't do complete search when combining branchers

pumpkin-cli/build.rs
**The issue:**
Currently, the project is rebuilt even when nothing has changed; to reproduce on the current `main` branch run:
`cargo build --release`
Followed by:
`CARGO_LOG=cargo::core::compiler::fingerprint=info cargo build --release`
Even if there are no changes, the `build.rs` script will rerun because of the following output `stale: missing "<LOCAL_PATH>/Pumpkin/pumpkin-cli/tests/**/*.c"`.
I think this is because `rerun-if-changed` does not handle wildcards/regexes; however, we can point it to a directory. This PR thus changes the wildcards to the directories which contain all the files matched by the previous wildcards.
=> (Mini PR) Fixing unnecessary rebuilding

pumpkin-cli/src/flatzinc/compiler/post_constraints.rs, pumpkin-lib/examples/disjunctive_scheduling.rs, pumpkin-lib/src/api/solver.rs, pumpkin-lib/src/constraints/arithmetic/equality.rs, pumpkin-lib/src/constraints/arithmetic/inequality.rs, pumpkin-lib/src/constraints/boolean.rs, pumpkin-lib/src/constraints/clause.rs, pumpkin-lib/src/constraints/constraint_poster.rs, pumpkin-lib/src/constraints/mod.rs, pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
In the proof log we want to identify which constraint implies any inference. To do so, we add an option to tag propagators with a `NonZero<u32>`. This PR does not actually implement this functionality, it just changes the API so that the tag can be passed through.
=> Add tagging of constraints and propagators

pumpkin-lib/src/propagators/arithmetic/linear_not_equal.rs
We thought that we could use a lazy reason for explaining the not equals constraint but we did not fix the underlying problem mentioned in #25 . This PR reverts to eager reason calculation!
=> Not using lazy reason for linear not equals

pumpkin-lib/src/branching/branchers/dynamic_brancher.rs, pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
In the case that `brancher_index == branchers.len()`, the `is_restart_pointless` method encounters an out-of-bounds error; this PR addresses this by ensuring that the brancer index is in the correct range.
_Additionally, the decision level was raised if a restart was considered but not actually performed; while this does not lead to any (obvious) bugs, this has been fixed in this PR for accuracy_
=> (Mini PR) Fix out-of-bounds is_restart_pointless for dynamic brancher

pumpkin-lib/src/engine/constraint_satisfaction_solver.rs, pumpkin-lib/src/engine/cp/reason.rs, pumpkin-lib/src/engine/debug_helper.rs, pumpkin-lib/src/propagators/arithmetic/integer_multiplication.rs
For a while, the code for checking the reason for a propagation has been unused; likely due to the fact that the reasons which were provided to the method were not `PropositionalConjunction`s anymore.
This PR aims to address this by calculating the reason eagerly (if the assertion levels are set to extreme) and checking these reasons. This already led to an error becoming apparent in the integer multiplication propagator due to an off-by-one error!
=> Re-introducing checking of Reason

Cargo.lock
= ID: RUSTSEC-2024-0378
= Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0378
= The family of functions to read "borrowed" values from Python weak
references
were fundamentally unsound, because the weak reference does itself
not have
ownership of the value. At any point the last strong reference
could
be cleared and the borrowed value would become dangling.
In PyO3 0.22.4 these functions have all been deprecated and patched
to leak a strong reference as a mitigation. PyO3 0.23 will remove these
functions entirely.
= Announcement: https://github.com/PyO3/pyo3/pull/4590
= Solution: Upgrade to >=0.22.4 (try `cargo update -p pyo3`)
= pyo3 v0.22.2
└── pumpkin-py v0.1.0
=> Update pyo3 to 0.22.4

.github/workflows/post-release-pumpkin-solver.yml, .github/workflows/release-notes.py, drcp-format/CHANGELOG.md
When pushing a tag in the format `pumpkin-solver-v<version>`, the github action will:
- Create a github release
- Attach the solver binaries for linux, macos and windows
- Publish to crates.io
=> Implement the pumpkin release pipeline

pumpkin-solver/src/statistics/mod.rs, pumpkin-solver/src/statistics/statistic_logger.rs
After a discussion with @ImkoMarijnissen, we came to the conclusion that for now #73 has a few limitations that are not directly easy to overcome. Therefore, this PR fixes the issue described there, without implementing a custom writer.
Repeating the PR description from that PR:
When testing statistics, I found float statistics to be divided into multiple lines:
_engine_statistics_time_spent_in_solver=139
_learned_clause_statistics_average_conflict_size=2
_learned_clause_statistics_average_conflict_size=.
_learned_clause_statistics_average_conflict_size=247863247863248
_learned_clause_statistics_average_number_of_removed_literals_recursive=2
_learned_clause_statistics_average_number_of_removed_literals_recursive=.
_learned_clause_statistics_average_number_of_removed_literals_recursive=5555 …
=> fix: float stat into one line

pumpkin-solver/src/engine/constraint_satisfaction_solver.rs, pumpkin-solver/src/engine/debug_helper.rs
Closes #79 
Currently, when a root-level conflict is found when adding a propagator, the state of the propagator does not contain the reported conflict.
However, this means that the `complete_proof` step cannot properly create the final learned clause; this PR addresses this by properly setting the state of the `ConstraintSatisfactionSolver` to be conflicting using the conflict returned by the propagator.
=> fix: complete proof when propagator initialization identifies root-level conflict

README.md
Necessary for the links to be accessible from `crates.io`
=> chore: changing links to absolute links

pumpkin-solver/src/engine/conflict_analysis/conflict_analysis_context.rs, pumpkin-solver/src/engine/constraint_satisfaction_solver.rs, pumpkin-solver/src/engine/cp/propagation/propagation_context.rs, pumpkin-solver/src/engine/cp/propagation/propagator.rs, pumpkin-solver/src/engine/cp/reason.rs, pumpkin-solver/src/engine/cp/test_helper.rs, pumpkin-solver/src/engine/debug_helper.rs, pumpkin-solver/src/propagators/arithmetic/linear_not_equal.rs, pumpkin-solver/src/propagators/cumulative/time_table/explanations/big_step.rs, pumpkin-solver/src/propagators/cumulative/time_table/explanations/mod.rs, pumpkin-solver/src/propagators/cumulative/time_table/explanations/naive.rs, pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/debug.rs, pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/time_table_over_interval_incremental.rs, pumpkin-solver/src/propagators/cumulative/time_table/propagation_handler.rs, pumpkin-solver/src/propagators/cumulative/time_table/time_table_over_interval.rs, pumpkin-solver/src/propagators/cumulative/time_table/time_table_per_point.rs, pumpkin-solver/src/propagators/cumulative/time_table/time_table_per_point_incremental.rs, pumpkin-solver/src/propagators/cumulative/time_table/time_table_util.rs, pumpkin-solver/src/propagators/cumulative/utils/structs/updatable_structures.rs, pumpkin-solver/src/propagators/cumulative/utils/util.rs, pumpkin-solver/src/propagators/element.rs, pumpkin-solver/src/propagators/reified_propagator.rs
Since `PropagationContext` implements `Copy`, functions should never take a parameter borrowing `PropagationContext`. It should always be taken with ownership.
=> fix: take ownership of the propagation context in propagators

pumpkin-solver/src/propagators/arithmetic/linear_less_or_equal.rs
The incremental state makes the consistency check cheap. This now improves the propagation strength when the `LinearLessThanEqual` is reified.
On benchmarks without reification this shows no difference compared to the non-incremental linear. Therefore I believe it does not need to be guarded behind an option.
=> feat: implement consistency check interface in linear less than propagator

drcp-format/README.md, drcp-format/src/reader/mod.rs, drcp-format/src/steps.rs, drcp-format/src/writer/mod.rs, pumpkin-solver/src/engine/conflict_analysis/conflict_analysis_context.rs, pumpkin-solver/src/engine/constraint_satisfaction_solver.rs, pumpkin-solver/src/engine/proof/mod.rs
The DRCP format is extended to support nogoods that are lazily blocked by propagators. When there is a propagation `R -> false`, then it suffices to log `R`. The README describes how this affects the textual format.
=> feat!: introduce inference-nogoods in drcp-format

Cargo.lock, pumpkin-solver/Cargo.toml, pumpkin-solver/src/engine/conflict_analysis/conflict_analysis_context.rs, pumpkin-solver/src/engine/constraint_satisfaction_solver.rs, pumpkin-solver/src/engine/proof/mod.rs
By linking to the version on the file system, when we update the `drcp-format` version, `pumpkin-solver` no-longer builds as there is no package with the required version on the file system anymore.
=> fix: ensure drcp-format version is the published one

pumpkin-solver/src/propagators/cumulative/time_table/time_table_util.rs
When allowing holes in the domain for the cumulative constraint, the explanation was attempting to use the cached profiles even when it should not.
This PR addresses this by dropping the cached explanations whenever we move to the next profile.
=> fix: cumulative holes in domain incorrectly used cached profile

pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/debug.rs, pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/synchronisation.rs, pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/time_table_over_interval_incremental.rs
Currently, the synchronised conflict explanation simply uses the first conflicting profile as its explanation. While this is correct in the sense that the start point of this profile is the same as the start point of the profile which would have been found by the non-incremental propagator, it suffers from the issue that the first conflicting profile does not necessarily span all of the adjacent profiles which have not been merged.
This PR aims to address this issue by finding the first profile which is conflicting **and** then creating a profile with all subsequent profiles which could be merged.
=> fix: wrong profile found for over-interval conflict explanation

pumpkin-solver/src/propagators/nogoods/nogood_propagator.rs
When preprocessing a nogood, if it becomes a unit nogood, the propagator would assign the negation of the predicate with an empty reason. However, from the perspective of the proof log, that is invalid as the input to the propagator was a non-unit nogood.
=> fix: give reason to root-level propagation in nogood propagator

pumpkin-py/Cargo.toml, pumpkin-py/README.md, pumpkin-py/examples/nqueens.py
Hey!
So while installing and trying to build, I came across the following:
Running `cargo build` in the project root directory (not necessarily useful, I did it by accident) means you also build `pumpkin-py`. However, I have a new laptop so I didn't yet have need to install the development headers for Python (`python3-dev` package on APT). This causes the the build to fail with the below linker error:
```
= note: /usr/bin/ld: cannot find -lpython3.13: No such file or directory
collect2: error: ld returned 1 exit status
```
This confused me (I've used PyO3 before), it's just an extension module (you're calling Rust from Python so you always have an interpreter) so why would you need the dev headers, which you usually only need if you're calling Python from a Rust executable …
=> fix: make pumpkin-py build without any additional installs

pumpkin-solver/src/branching/branchers/alternating_brancher.rs, pumpkin-solver/src/engine/cp/assignments.rs
The `AlternatingBrancher` did not call the correct methods on the default brancher meaning that the solver had poor performance during free search (since it did not restore any keys to the heap upon backtracking). This has been fixed by performing the right calls
=> fix: alternating brancher did not call the methods correctly

pumpkin-solver/src/engine/conflict_analysis/minimisers/semantic_minimiser.rs
When creating a new domain, it could be that the lb/ub is a hole, or that there are holes outside of the bounds. This is currently not post processed before creating the domain, so this happens after minimisation for the first time. This can cause the number of literals after minimisation to be higher than before, causing an overflow:
https://github.com/ConSol-Lab/Pumpkin/blob/d66ecb6e541b9d15562dc7db223b8a86b3bade13/pumpkin-solver/src/engine/conflict_analysis/minimisers/recursive_minimiser.rs#L65
Post-processing the new domain fixes this problem.
=> fix: post process new domain

pumpkin-solver/src/bin/pumpkin-solver/flatzinc/compiler/post_constraints.rs, pumpkin-solver/src/constraints/boolean.rs, pumpkin-solver/src/engine/variables/literal.rs
There are three spots in the flatzinc parser & constraint constructors that I believe to contain unnecessary variable creation:
- `create_domains` for `BooleanLessThanOrEqual`  and `BooleanEqual`
- `compile_bool2int`
It seems like we can directly used the parsed literals instead of creating a new variable and a linking clause. It only requires access to the underlying `integer_variable` of the literal, but I don't see that as a problem. Is there any reason for doing it this way, or is it because of the legacy structure?
=> feat: no additional variables during constraint construction

pumpkin-solver/src/propagators/cumulative/time_table/over_interval_incremental_propagator/checks.rs
The check for whether a profile overflowed the resource capacity contained an additional term; this PR removes this term
=> fix: fixing erronous conflict check when using incrementality

pumpkin-solver/tests/helpers/flatzinc.rs
The Flatzinc parser was not able to parse Boolean arrays. Besides, I fixed that negative integers are also parsed correctly.
=> feat: Flatzinc parse boolean & negative int arrays as well

pumpkin-solver/examples/disjunctive_scheduling.rs
Hi, another tiny fix while getting everything running. 
I'm pretty sure the negation of `literal => s_y - s_x <= -p_y` is as follows:
$$l => s_y - s_x <= -p_y$$
$$\neg l => s_y - s_x > -p_y$$
$$\neg l => s_y - s_x >= -p_y + 1$$
$$\neg l => -s_y + s_x <= p_y - 1$$
Also the literal was not actually negated in the second case, so I added that as well in the way I think you're supposed to do it.
=> fix: disjunctive_scheduling example had incorrect negation constraint

pumpkin-solver/src/branching/value_selection/random_splitter.rs, pumpkin-solver/src/engine/cp/trailed/trailed_assignments.rs
This PR addresses 2 issues:
- Debug clone was backtracking to level 0 which could throw an exception for `TrailedAssignments`
- The `RandomSplitter` had edge cases related to bounds
=> feat: debug clone does not synchronise at level 0 + random splitter edge cases

pumpkin-solver/src/propagators/nogoods/nogood_propagator.rs
The debug propagate currently also attempts to propagate deleted nogoods
=> fix: don't debug propagate deleted nogoods

pumpkin-py/src/lib.rs, pumpkin-py/src/model.rs, pumpkin-py/src/optimisation.rs, pumpkin-py/tests/test_optimisation.py, pumpkin-solver/src/bin/pumpkin-solver/flatzinc/mod.rs, pumpkin-solver/src/optimisation/linear_sat_unsat.rs, pumpkin-solver/src/optimisation/linear_unsat_sat.rs, pumpkin-solver/src/optimisation/mod.rs
The Python API does not enforce a particular optimisation routine. At the moment, we support:
- LSU
- LUS
Both are, therefore, present in Python as well.
=> feat: expose the optimisation API in the python wrapper

pumpkin-solver/src/basic_types/propositional_conjunction.rs, pumpkin-solver/src/engine/conflict_analysis/conflict_analysis_context.rs, pumpkin-solver/src/engine/conflict_analysis/minimisers/recursive_minimiser.rs, pumpkin-solver/src/engine/conflict_analysis/resolvers/resolution_resolver.rs, pumpkin-solver/src/engine/constraint_satisfaction_solver.rs, pumpkin-solver/src/engine/cp/propagation/contexts/propagation_context.rs, pumpkin-solver/src/engine/cp/reason.rs, pumpkin-solver/src/engine/cp/test_solver.rs, pumpkin-solver/src/engine/debug_helper.rs, pumpkin-solver/src/propagators/cumulative/time_table/propagation_handler.rs
Previously, submitting a lazy reason in a reified propagator would crash the solver. Implementing this is non-trivial, as reasons used in conflict analysis were returned as slices. However, we need to insert a reification literal into that slice somehow.
One approach would be to always return some owned buffer like a `Vec` from the reason store, so that it can insert the reification literal there. However, that would entail allocating when we ideally want to avoid that.
Instead, the solution implemented here is to provide the buffer that the reason should be written in to. Then it is up to the caller to either allocate or reuse an existing allocation.
=> fix: allow reification of lazy reasons

pumpkin-py/src/lib.rs, pumpkin-py/src/model.rs, pumpkin-py/src/result.rs, pumpkin-py/src/variables.rs, pumpkin-py/tests/test_assumptions.py
Assumption solving in the Rust layer currently performs semantic minimisation of the core. E.g. if the assumptions contain `[y <= 1]` and `[y != 0]`, and the domain of `y` starts at 0, then the core may contain `[y == 1]` rather than the original predicates in the assumptions.
=> feat: implement predicate and assumption solving in python wrapper

pumpkin-py/tests/test_constraints.py
I added a script that automatically generates a bunch of constraints and posts them through the Python API.
Some bugs I have found (annotated with TODO in the script):
- Scaling with "0" results in division-by zero errors for some constraints
- The reified propagator for Element seems to be unimplemented for now?
Ideally, we can also test whether the constraint is indeed satisfied by the solution found by the solver, but I'm not sure how to that.
=> add grammar-based testing script

Cargo.lock, Cargo.toml, drcp-debugger/Cargo.toml, drcp-debugger/src/main.rs, drcp-format/src/reader/mod.rs
The tool takes a proof and replaces all the literals with appropriate atomic constraints. This makes for easier reading of the proof by humans.
fix(drcp-format): An empty nogood with hints can now be parsed.
=> feat: implement a tool to combine a proof with its literal mapping

Cargo.lock, pumpkin-py/Cargo.toml
In response to https://rustsec.org/advisories/RUSTSEC-2025-0020
=> refactor: update PyO3 to version 0.24.1

pumpkin-solver/src/engine/constraint_satisfaction_solver.rs
When we compute the starting point of the conflict analysis, we ignore the very last propagation in the proof log. This meant the proof would be missing a proof step.
=> fix: also log the inference that led to an empty domain

pumpkin-solver/src/engine/cp/propagation/propagator.rs, pumpkin-solver/src/propagators/arithmetic/linear_less_or_equal.rs, pumpkin-solver/src/propagators/nogoods/nogood_propagator.rs
I made minor changes to the comments, mainly outdated comments that refer to the pre-revamp version.
=> fix: Update outdated documentation from before the v0.2 release

pumpkin-solver/src/propagators/reified_propagator.rs
- Expanded the documentation a bit.
- Placed reified literal id right after the reified literal.
- Placed reified literal as the first field and the propagator as the second, to follow r -> p.
=> docs: Expand documentation of reified propagator

pumpkin-solver/src/engine/conflict_analysis/conflict_analysis_context.rs, pumpkin-solver/src/engine/cp/assignments.rs
In the proof log, this difference is crucial. We cannot say that initial holes are those at decision level 0.
=> fix: Properly explain root-level explanations that are not considered during conflict analysis

pumpkin-solver/src/propagators/nogoods/nogood_id.rs, pumpkin-solver/src/propagators/nogoods/nogood_propagator.rs
The cached predicate is currently not stored in the watcher meaning that we have to go through an extra level of indirection to retrieve the cached predicate
=> refactor: Move cached predicate to watcher

pumpkin-solver/src/engine/constraint_satisfaction_solver.rs, pumpkin-solver/src/proof/inference_code.rs
Previously it printed 'nogood_label', which is the snake_case version of the label type name. In this case it makes sense that the type name and the actual string differ, since the name 'Nogood' for the inference label would be confusing, whereas with 'NogoodLabel' it is clear what the type represents.
=> refactor: Change the nogood inference label to print 'nogood'

drcp-debugger/src/main.rs
When we updated the drcp-format crate, we forgot to update the drcp-debugger. Now that the proof format does not span two files, it is already easier to read. However, replacing the literals with atomic constraints is still very useful for debugging apps producing/consuming proofs.
=> fix: Update drcp-debugger to new drcp-format version

pumpkin-solver/src/proof/finalizer.rs, pumpkin-solver/src/proof/mod.rs
Also fix the hint for the deduction, to log the id of the inference instead of the id that triggered the inference.
=> fix: Log the initial bounds in the full proof as inferences

pumpkin-solver/src/bin/pumpkin-solver/main.rs
When performing recursive minimisation, our logging of inferences is completely wrong. We should only log the inferences that are actually used when removing a predicate. For now it is easier to disable it, then we can revisit it later. Issue #214 is the reminder that we do not forget to implement this at some point.
=> fix: Disable recursive minimisation when logging the full proof

pumpkin-solver/src/constraints/arithmetic/equality.rs, pumpkin-solver/src/engine/cp/assignments.rs, pumpkin-solver/src/engine/cp/propagation/contexts/propagation_context.rs, pumpkin-solver/src/engine/cp/test_solver.rs, pumpkin-solver/src/engine/notifications/domain_event_notification/domain_events.rs, pumpkin-solver/src/engine/variables/affine_view.rs, pumpkin-solver/src/engine/variables/domain_id.rs, pumpkin-solver/src/engine/variables/integer_variable.rs, pumpkin-solver/src/engine/variables/literal.rs, pumpkin-solver/src/propagators/arithmetic/binary/binary_equals.rs, pumpkin-solver/src/propagators/arithmetic/binary/binary_not_equals.rs, pumpkin-solver/src/propagators/arithmetic/binary/mod.rs, pumpkin-solver/src/propagators/arithmetic/mod.rs
Currently, we decompose `int_eq` and `int_ne` in terms of two linear inequalities, and a general not equal propagator, respectively.
This PR aims to implement a dedicated propagator for these two cases, this allows the following benefits:
- For `int_eq`: the decomposition only allows bounds consistency while now we can be domain consistent
- For `int_ne`: earlier experiment showed that implementing `detect_inconsistency` for `int_lin_ne` was not performant, however, it can be easily done for the binary case.
MiniZinc Score: 
- With Update: 179.72
- Without Update: 176.28
Average Primal Integral:
- With Update: 37.44
- Without Update: 57.98
=> feat: Propagator for `int_ne` and `int_eq`

pumpkin-crates/core/src/propagators/cumulative/time_table/over_interval_incremental_propagator/time_table_over_interval_incremental.rs, pumpkin-crates/core/src/propagators/cumulative/time_table/per_point_incremental_propagator/time_table_per_point_incremental.rs, pumpkin-crates/core/src/propagators/cumulative/time_table/time_table_over_interval.rs, pumpkin-crates/core/src/propagators/cumulative/time_table/time_table_per_point.rs, pumpkin-crates/core/src/propagators/cumulative/utils/structs/parameters.rs
Currently, we do not proactively look for the case where a task is provided that uses more resource than the capacity; this leads to an issue when this conflict is reported as it could have been reported earlier.
This PR addresses this issue by performing an additional check when initialising. This occurs in [certain models](https://github.com/MiniZinc/mzn-challenge/blob/develop/2024/aircraft-disassembly/aircraft.mzn).
=> fix: Reporting conflict if there is a task which uses more resource than capacity

pumpkin-crates/core/src/engine/notifications/domain_event_notification/domain_events.rs, pumpkin-crates/core/src/propagators/arithmetic/binary/binary_equals.rs
The `backtrack_notify` method does not always notify you of your own changes (since it might also not `notify` you of them if they caused an empty domain/conflict).
For the binary equals propagator this meant that it was not always correctly checking the removed values upon backtracking.
=> fix: Use synchronise instead of notify backtrack for binary equals

pumpkin-solver/src/bin/pumpkin-solver/flatzinc/mod.rs
Closes #260 
The MiniZinc IDE does not accept leading digits in statistic names
=> fix: Removing leading number from statistics

Cargo.lock, pumpkin-crates/core/Cargo.toml, pumpkin-crates/core/src/proof/mod.rs, pumpkin-solver/Cargo.toml
Using a gzip encoder to write the proof is gated behind a cargo feature. That feature is part of the default features, as typically we want to write gzipped proofs. However, for debugging purposes, it may be useful to have easy access to the plaintext proofs as well.
=> feat(pumpkin-solver): Write proofs with gzip encoding

pumpkin-solver-py/src/constraints/globals.rs, pumpkin-solver-py/src/model.rs, pumpkin-solver-py/tests/test_assumptions.py, pumpkin-solver-py/tests/test_constraints.py
Previously the python constraints all got a fresh constraint tag. This messes with the proof log, so now users can provide constraint tags the same way they do in the Rust interface.
=> feat: Allow the constraint tag to be set in the Python interface

pumpkin-crates/core/src/propagators/cumulative/time_table/explanations/mod.rs, pumpkin-crates/core/src/propagators/cumulative/time_table/propagation_handler.rs, pumpkin-crates/core/src/propagators/cumulative/time_table/time_table_util.rs, pumpkin-macros/src/lib.rs, pumpkin-solver/src/bin/pumpkin-solver/main.rs
This PR introduces a number of changes to the time-table propagator(s):
- One of the main differences is that the propagation will use the method [Vec::partition_point(..)](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.partition_point) to avoid looking at profiles which are guaranteed not to be able to update the profiles
- The method which generated the sequence of profiles was looking for _consecutive_ profiles which caused the maximum (minimum) lower-bound (upper-bound) update. However, imagine the scenario in which there are 3 profiles where the 1st and the 3rd are able to (together) propagate the lower-bound to its maximum value but the 2nd profile cannot propagate the task; the current implementation would only generate an explanation based on the 1st profile and then …
=> feat: Avoid unnecessary traversals of profiles in time-tabling + Improving Explanations
